# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-25 15:21
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_content_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='正文必须为MarkDown格式', verbose_name='正文'),
        ),
    ]
