# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-25 15:24
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200725_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='正文必须为MarkDown格式', verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_html',
            field=ckeditor.fields.RichTextField(blank=True, editable=False, verbose_name='正文html代码'),
        ),
    ]
