# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-25 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200725_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=2000, verbose_name='内容'),
        ),
    ]
